version: "3"

services:
  backend:
    image: backend:2.0
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - project-net

  frontend:
    image: frontend:2.0
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - project-net

networks:
  project-net:
